import Head from "next/head";
import Image from "next/image";
import EventModule from "../components/Foreground/EventModule";
import { useAtom } from "jotai";
import { eventModalVisibility } from "../utils/store";

export default function Home() {
  const [eventModalVisible, setEventModalVisible] =
    useAtom(eventModalVisibility);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <button
          onClick={() => setEventModalVisible(true)}
          className="bg-gray-100 rounded-xl py-2 px-3 m-4"
        >
          Show Modal
        </button>
      </div>
      <div className="flex justify-center">
        <EventModule />
      </div>
    </div>
  );
}
