import Head from "next/head";
import Image from "next/image";
import EventModule from "../components/EventModule";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>test</div>
      <div className="flex justify-center">
        <EventModule />
      </div>
    </div>
  );
}
